// ERROR ACTION
export const ERROR_ACTION = "ERROR_ACTION";

// LOGIN ACTIONS
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


// USER ACTIONS
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const ENABLE_USER = "ENABLE_USER";
export const DISABLE_USER = "DISABLE_USER";



// TRANSFERT ACTIONS
export const SET_DATA_SOURCE = "SET_DATA_SOURCE";
export const SET_DATA_DESTINATAIRE = "SET_CLIENT_DESTINATAIRE";
export const SET_TRANSFERT_INFO = "SET_TRANSFERT_INFO";
export const SET_OPERATION_TYPE = "SET_OPERATION_TYPE";



// ACCOUNt ACTIONS
export const FETCH_ACCOUNTS_BY_USER = "FETCH_ACCOUNTS_BY_USER";
export const SET_SELECTED_ACCOUNT = "SET_SELECTED_ACCOUNT";


// ACCOUNt ACTIONS
export const FETCH_CARDS_BY_ACCOUNT_ID = "FETCH_CARDS_BY_ACCOUNT_ID";
